### ISSUE TITLE
License Change -- Are you sure?

### ISSUE THREAD

**Issue by clinew** [sleuthkit/scalpel#26]
It looks like the codebase was originally GPL.  Unless you've received copyright from the license holders or a different version that was under a non-copyleft license, I'm pretty sure your derivate work must also be under the GPL.  Please clarify how you were able to make this change.

**Comment by bcarrier** [comment]
We got permission from the Scalpel authors ( @nolaforensix   and @vicodark ).

**Comment by clinew** [comment]
Allright then.
